package com.lindp.zmall.common.response;

/**
 * Restful 返回代码枚举类型
 *
 * @author lindp
 * @date 2019-06-12
 */
public enum RestCodeEnum {

    // A 用户级别

    OK("00000", null),
    ClientException("A0001", "用户端错误"),
    RegisterException("A0100", "用户注册错误"),
    RegisterClauseUnCheckException("A0101", "用户未同意隐私协议"),
    RegisterNationOrRegionException("A0102", "注册国家或地区受限"),
    LoginNameCheckException("A0110", "用户名校验失败"),
    LoginNameExistedException("A0111", "用户名已存在"),
    LoginNameSensitiveWordsException("A0112", "用户名包含敏感词"),
    LoginNameSpecialCharacterException("A0113", "用户名包含特殊字符"),
    PasswordCheckException("A0120", "密码校验失败"),
    PasswordLengthException("A0121", "密码长度不够"),
    PasswordEasyException("A0122", "密码强度不够"),
    CheckCodeException("A0130", "校验码输入错误"),
    SmsCheckCodeException("A0131", "短信校验码输入错误"),
    EmailCheckCodeException("A0132", "邮件校验码输入错误"),
    VoiceCheckCodeException("A0133", "语音校验码输入错误"),
    IdcardException("A0140", "用户证件异常"),
    IdcardTypeUnCheckException("A0141", "用户证件类型未选择"),
    IdcardCodeException("A0142", "大陆身份证编号校验非法"),
    PassportCodeException("A0143", "护照编号校验非法"),
    OfficerCodeException("A0144", "军官证编号校验非法"),
    UserInfoException("A0150", "用户基本信息校验失败"),
    PhoneFormatException("A0151", "手机格式校验失败"),
    AddrFormatException("A0152", "地址格式校验失败"),
    EmailFormatException("A0153", "邮箱格式校验失败"),
    LoginException("A0200", "用户登陆异常"),
    LoginNameNotFoundException("A0201", "用户账户不存在"),
    LoginNameFreezeException("A0202", "用户账户被冻结"),
    LoginNameCancelException("A0203", "用户账户已作废"),
    LoginNameDisableException("A0204", "用户账户已禁用"),
    LoginPasswordException("A0210", "用户密码错误"),
    LoginPasswordInputLimitException("A0211", "用户输入密码次数超限"),
    LoginNameOrPasswordException("A0212", "用户名或密码错误"),
    UserIdentityCheckException("A0220", "用户身份校验失败"),
    FingerprintException("A0221", "用户指纹识别失败"),
    FaceException("A0222", "用户面容识别失败"),
    ThirdLoginException("A0223", "用户未获得第三方登陆授权"),
    LoginExpiredException("A0230", "用户登陆已过期"),
    LoginValidCodeException("A0240", "用户验证码错误"),
    LoginValidCodeLimitException("A0241", "用户验证码尝试次数超限"),
    AuthorizationException("A0300", "访问权限异常"),
    UnauthorizedException("A0301", "访问未授权"),
    AuthorizingException("A0302", "正在授权中"),
    AuthorizationApplyRefuseException("A0303", "用户授权申请被拒绝"),
    PrivacySettingRefuseException("A0310", "因访问对象隐私设置被拦截"),
    AuthorizationExpiredException("A0311", "授权已过期"),
    NoPermissionAPIException("A0312", "无权限使用 API"),
    AccessRefuseException("A0320", "用户访问被拦截"),
    BlacklistUserException("A0321", "黑名单用户"),
    AccountFreezeException("A0322", "账号被冻结"),
    IPAddressInvalidException("A0323", "非法 IP 地址"),
    GatewayAccessException("A0324", "网关访问受限"),
    RegionBlacklistException("A0325", "地域黑名单"),
    ServiceArrearsException("A0330", "服务已欠费"),
    SignException("A0340", "用户签名异常"),
    RSASignException("A0341", "RSA 签名错误"),
    ParameterException("A0400", "用户请求参数错误"),
    LinkIllegalSpiteException("A0401", "包含非法恶意跳转链接"),
    InputInvalidException("A0402", "无效的用户输入"),
    ParameterRequiredException("A0410", "请求必填参数为空"),
    OrderNoNullException("A0411", "用户订单号为空"),
    OrderNumNullException("A0412", "订购数量为空"),
    TimestampNotFoundException("A0413", "缺少时间戳参数"),
    TimestampInvalidException("A0414", "非法的时间戳参数"),
    ParameterLimitException("A0420", "请求参数值超出允许的范围"),
    ParameterFormatException("A0421", "参数格式不匹配"),
    AddressOutOfServiceException("A0422", "地址不在服务范围"),
    TimeOutOfServiceException("A0423", "时间不在服务范围"),
    AmountLimitException("A0424", "金额超出限制"),
    NumberLimitException("A0425", "数量超出限制"),
    RequestBatchingLimitException("A0426", "请求批量处理总个数超出限制"),
    RequestJsonParseException("A0427", "请求 JSON 解析失败"),
    InputIllegalException("A0430", "用户输入内容非法"),
    InputSensitiveWordsException("A0431", "包含违禁敏感词"),
    PictureIllicitException("A0432", "图片包含违禁信息"),
    FileCopyrightException("A0433", "文件侵犯版权"),
    OperateException("A0440", "用户操作异常"),
    PayTimeoutException("A0441", "用户支付超时"),
    OrderConfirmTimeoutException("A0442", "确认订单超时"),
    OrderClosedException("A0443", "订单已关闭"),
    RequestServiceException("A0500", "用户请求服务异常"),
    RequestLimitException("A0501", "请求次数超出限制"),
    RequestConcurrentLimitException("A0502", "请求并发数超出限制"),
    OperateWaitingException("A0503", "用户操作请等待"),
    WebSocketConnectException("A0504", "WebSocket 连接异常"),
    WebSocketConnectBreakException("A0505", "WebSocket 连接断开"),
    RequestRepeatException("A0506", "用户重复请求"),
    UserResourceException("A0600", "用户资源异常"),
    UserNotBalanceException("A0601", "账户余额不足"),
    UserNotDiskException("A0602", "用户磁盘空间不足"),
    UserNotMemoryException("A0603", "用户内存空间不足"),
    UserNotOSSException("A0604", "用户 OSS 容量不足"),
    UserNotQuotaException("A0605", "用户配额已用光"),
    UploadFileException("A0700", "用户上传文件异常"),
    UploadFileTypeException("A0701", "用户上传文件类型不匹配"),
    UploadFileBigException("A0702", "用户上传文件太大"),
    UploadImageBigException("A0703", "用户上传图片太大"),
    UploadVideoBigException("A0704", "用户上传视频太大"),
    UploadZipBigException("A0705", "用户上传压缩文件太大"),
    VersionException("A0800", "用户当前版本异常"),
    VersionNeSystemException("A0801", "用户安装版本与系统不匹配"),
    VersionLowException("A0802", "用户安装版本过低"),
    VersionHighException("A0803", "用户安装版本过高"),
    VersionExpiredException("A0804", "用户安装版本已过期"),
    VersionApiMatchException("A0805", "用户 API 请求版本不匹配"),
    VersionApiHighException("A0806", "用户 API 请求版本过高"),
    VersionApiLowException("A0807", "用户 API 请求版本过低"),
    PrivacyUnauthorizedException("A0900", "用户隐私未授权"),
    PrivacyUnsignedException("A0901", "用户隐私未签署"),
    CameraDeviceUnauthorizedException("A0902", "用户摄像头未授权"),
    CameraUnauthorizedException("A0903", "用户相机未授权"),
    PictureGalleryUnauthorizedException("A0904", "用户图片库未授权"),
    FileUnauthorizedException("A0905", "用户文件未授权"),
    LocationUnauthorizedException("A0906", "用户位置信息未授权"),
    AddressBookUnauthorizedException("A0907", "用户通讯录未授权"),
    DeviceException("A1000", "用户设备异常"),
    CameraException("A1001", "用户相机异常"),
    MicrophoneException("A1002", "用户麦克风异常"),
    ListenException("A1003", "用户听筒异常"),
    SpeakerException("A1004", "用户扬声器异常"),
    GPSLocationException("A1005", "用户 GPS 定位异常"),

    // B 系统级别

    SystemExecuteException("B0001", "系统执行出错"),
    SystemExecuteTimeoutException("B0100", "系统执行超时"),
    SystemOrderHandleTimeoutException("B0101", "系统订单处理超时"),
    SystemDisasterRecoverException("B0200", "系统容灾功能被触发"),
    SystemLimitException("B0210", "系统限流"),
    SystemFuncDemotionException("B0220", "系统功能降级"),
    SystemResourceException("B0300", "系统资源异常"),
    SystemNotResourceException("B0310", "系统资源耗尽"),
    SystemNotDiskException("B0311", "系统磁盘空间耗尽"),
    SystemNotMemoryException("B0312", "系统内存耗尽"),
    SystemFileHandleExhaustedException("B0313", "文件句柄耗尽"),
    SystemConnectionPoolNullException("B0314", "系统连接池耗尽"),
    SystemThreadPoolNullException("B0315", "系统线程池耗尽"),
    SystemResourceAccessException("B0320", "系统资源访问异常"),
    SystemReadFileException("B0321", "系统读取磁盘文件失败"),

    // C 第三方服务错误

    ThirdServiceException("C0001", "调用第三方服务出错"),
    ThirdMiddlewareServiceException("C0100", "中间件服务出错"),
    ThirdRPCException("C0110", "RPC 服务出错"),
    ThirdRPCNotFoundException("C0111", "RPC 服务未找到"),
    ThirdRPCUnRegisteredException("C0112", "RPC 服务未注册"),
    ThirdInterfaceNotFoundException("C0113", "接口不存在"),
    ThirdMsgException("C0120", "消息服务出错"),
    ThirdMsgSendException("C0121", "消息投递出错"),
    ThirdMsgConsumeException("C0122", "消息消费出错"),
    ThirdMsgSubscribeException("C0123", "消息订阅出错"),
    ThirdMsgGroupNotFoundException("C0124", "消息分组未查到"),
    ThirdCacheException("C0130", "缓存服务出错"),
    ThirdKeyLengthException("C0131", "key 长度超过限制"),
    ThirdValueLengthException("C0132", "value 长度超过限制"),
    ThirdStorageFullException("C0133", "存储容量已满"),
    ThirdUnsupportedDataFormatException("C0134", "不支持的数据格式"),
    ThirdConfiguringServiceException("C0140", "配置服务出错"),
    ThirdNetworkResourceServiceException("C0150", "网络资源服务出错"),
    ThirdVPNServiceException("C0151", "VPN 服务出错"),
    ThirdCDNServiceException("C0152", "CDN 服务出错"),
    ThirdDomainNameServiceException("C0153", "域名解析服务出错"),
    ThirdGatewayServiceException("C0154", "网关服务出错"),
    ThirdExecuteTimeoutException("C0200", "第三方系统执行超时"),
    ThirdRPCExecuteTimeoutException("C0210", "RPC 执行超时"),
    ThirdMsgSendTimeoutException("C0220", "消息投递超时"),
    ThirdCacheServiceTimeoutException("C0230", "缓存服务超时"),
    ThirdConfiguringServiceTimeoutException("C0240", "配置服务超时"),
    ThirdDataBaseTimeoutException("C0250", "数据库服务超时"),
    ThirdDataBaseException("C0300", "数据库服务出错"),
    ThirdDataBaseTableNotFoundException("C0311", "表不存在"),
    ThirdDataBaseColumnNotFoundException("C0312", "列不存在"),
    ThirdDataBaseMultipleTableJoinSameColumnException("C0321", "多表关联中存在多个相同名称的列"),
    ThirdDataBaseDeadLockException("C0331", "数据库死锁"),
    ThirdDataBasePrimarykeyException("C0341", "主键冲突"),
    ThirdDisasterRecoverException("C0400", "第三方容灾系统被触发"),
    ThirdLimitException("C0401", "第三方系统限流"),
    ThirdFuncDemotionException("C0402", "第三方功能降级"),
    ThirdNoticeServiceException("C0500", "通知服务出错"),
    ThirdSmsRemindServiceException("C0501", "短信提醒服务失败"),
    ThirdVoiceRemindServiceException("C0502", "语音提醒服务失败"),
    ThirdEmailRemindServiceException("C0503", "邮件提醒服务失败");

    /**
     * 自定义错误码
     */
    private final String code;
    /**
     * 错误描述
     */
    private final String message;

    RestCodeEnum(String code, String message) {
        this.code = code;
        this.message = message;
    }

    public String getCode() {
        return code;
    }

    public String getMessage() {
        return message;
    }
}
